### PR TITLE
Adding a dual-license of WTFPL and MIT.

### PR DESCRIPTION
**Pull request by kevinswiber**
Any chance we can get this dual-licensed under WTFPL _and_ MIT?

### CODE REVIEW

**Comment by kb** [comment]
@rlidwka this would be a welcomed updated as its causing issues with using dependencies in our stack that leverage this library.

**Comment by mgol** [comment]
This is not the only place that needs updating; there's also `package.json` - generated here by `package.yaml`, see [those lines](https://github.com/rlidwka/jju/blob/6a1248f/package.yaml#L43-L45). It needs to be a valid SPDX expression, sth like:
```
"license" : "(WTFPL OR MIT)"
```
See https://docs.npmjs.com/files/package.json for more details.

**Comment by nkothari** [comment]
@rlidwka Is it possible to update the license terms and include MIT as requested? We're facing multiple downstream implications.

**Comment by saurabhinfoworks** [comment]
@rlidwka can you please approve this PR, we are facing issue in deploying our meteor application on google cloud.

**Comment by spectejb** [comment]
Great news!  @rlidwka has agreed to include a dual license of WTFPL and MIT!   Really appreciate Alex's help here.

**Comment by rlidwka** [comment]
Sorry for the delay, I've just switched for MIT completely (with both licenses being permissive, there's no real need for dual-license imho).

**Pull request closed without merging**
